#!/bin/bash

# Tool to make releasing painless
# usage: ./release x.y.z
# where x.y.z is the version number to release to

NEW_VERSION=$1

# bump the version number in notedown/main.py
sed -i -e "s/__version__ = .*/__version__ = "'"'$NEW_VERSION'"'"/" notedown/main.py &&

# upload to pypi
python setup.py sdist upload -r pypi &&

# setup.py should derive the version number from notedown
# automatically

# commit the version bump
git add notedown/main.py &&
git commit -m "release $NEW_VERSION" &&

# git tag the release
git tag rel-$NEW_VERSION
